export const TABLE_NAME = {
  USER: "tbl_user",
  QUALIFICATIONS: "tbl_qualifications",
  UNITS: "tbl_units",
  MAIN_OUTCOMES: "tbl_main_outcomes",
  OUTCOMES: "tbl_sub_outcomes",
  OUTCOME_SUBPOINTS: "tbl_outcome_subpoints",
  USER_QUALIFICATION: "tbl_user_qualification",
  ROLE: "tbl_role",
  CENTER: "tbl_center",
  USER_LEARNER: "tbl_user_learner",
  USER_ASSESSOR: "tbl_user_assessor",
  USER_IQA: "tbl_user_iqa",
  METHODS: "tbl_methods",
  ASSESSMENT: "tbl_assessment",
  IMAGE: "tbl_image",
  ASSESSMENT_METHODS: "tbl_assessment_methods",
  ASSESSMENT_UNITS: "tbl_assessment_units",
  ASSESSMENT_LEARNER: "tbl_assessment_learner",
  ASSESSMENT_NOTES: "tbl_assessment_notes",
  ASSESSMENT_NOTE_FILES: "tbl_assessment_note_files",
};
